services:
  - type: web
    name: memoraid-backend
    runtime: docker
    plan: free
    dockerfilePath: ./projectmemoraid/backend/Dockerfile
    dockerContext: ./projectmemoraid/backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: onboarding@resend.dev
      - key: CORS_ALLOWED_ORIGINS
        sync: false