services:
  - type: web
    name: memoraid-backend
    runtime: docker
    dockerfilePath: ./projectmemoraid/backend/Dockerfile
    dockerContext: ./projectmemoraid/backend
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: memoraid-db
          property: connectionString
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: onboarding@resend.dev
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: memoraid-db
    databaseName: memoraid_db
    plan: starter